repos:
  - repo: local
    hooks:
      - id: fix
        name: fix
        entry: make fix
        language: system
        types: [python]
      
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]